### DISCUSSION TITLE
[Topology operator: queue creation ] Error: API responded with a 401 Unauthorized

### DISCUSSION THREAD

**Discussion by marcelloraffaele** [rabbitmq/messaging-topology-operator#300] [Q&A] [answered]
Hi Team,
I have problem installing queue, I just installed the operator but I obtain the following error:

```
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata: 
  creationTimestamp: "2022-02-10T10:45:41Z"
  finalizers:
  - deletion.finalizers.queues.rabbitmq.com
  name: test-queue1
  namespace: rabbitmq-system
spec:
  name: test-queue
  rabbitmqClusterReference:
    name: rabbitmq
    namespace: rabbitmq-system
  vhost: /
status:
  conditions:
  - lastTransitionTime: "2022-02-10T10:45:41Z"
    message: 'Error: API responded with a 401 Unauthorized'
    reason: FailedCreateOrUpdate
    status: "False"
    type: Ready
```

The operator logs are the following:
`{"level":"error","ts":1644490023.4455469,"logger":"controller.queue","msg":"Reconciler error","reconciler group":"rabbitmq.com","reconciler kind":"Queue","name":"test-queue1","namespace":"rabbitmq-system","error":"Error: API responded with a 401 Unauthorized","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:227"}`

Do you have any idea about this error?
Maybe is a problem of authorization, how can I fix it ?

**Comment by marcelloraffaele** [comment, marked as answer]
I found the reason was that I had defined a custom default user:

```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
    name: rabbitmq
    namespace: rabbitmq-system
    annotations:
      rabbitmq.com/topology-allowed-namespaces: "*"
spec:
  rabbitmq:
    additionalPlugins:
      - rabbitmq_mqtt
      - rabbitmq_management
    additionalConfig: |
      default_user = guest
      default_pass = guest
```

It was like the operator was using another user to make it's configuration. I removed it and it worked.
