### DISCUSSION TITLE
How to config Shovel over SSL

### DISCUSSION THREAD

**Discussion by marcelloraffaele** [rabbitmq/messaging-topology-operator#316] [Q&A] [answered]
Hi Team,
I am going to configure a Shovel to replicate messages from a RabbitMQ cluster to another, both clusters can use only SSL (amqps).
In the documentation I noticed that there's a way to pass the destination server certificate inside the url specified inside the shovel configuration ([shovel-dynamic](https://www.rabbitmq.com/shovel-dynamic.html)). I would like to know if I need to mount the secret somewhere and if yes where ? Do you have some examples about this configuration?

Thank you,
R

**Comment by ChunyiLyu** [comment, marked as answer]
Hi @marcelloraffaele, thanks for using our Operators. If your RabbitmqCluster is TLS only, you first need to follow this [Topology Operator TLS guide](https://www.rabbitmq.com/kubernetes/operator/tls-topology-operator.html) to ensure that the Topology Operator trust your RabbitmqCluster CA. After this step, Topology Operator can connect to the RabbitMQ server successfully and create queues, exchanges, and shovels etc.

For configuring shovel, `cacertfile `, `certfile`, and `keyfile` for both the src and destination URI should be path to them in that particular RabbitmqCluster you are declaring shovel in. If cert files for your destination RabbitMQ is not in that RabbitmqCluster yet, you could mount the secret containing these TLS certs by using statefulSetOverride, for example:

```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: example
spec:
...
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers:
            - name: rabbitmq
              volumeMounts:
              - mountPath: /path/to/certs
                name: a-secret-volume-name
            volumes:
            - name: a-secret-volume-name
              secret:
                secretName: additional-tls-secret
```

Please let me know if it works! The team hasn't personally tested using topology operator to configure TLS only federation and shovels before (there is no reason why it shouldn't work tho). It will be a good example to add our `docs/examples` to help others in the future.
