### DISCUSSION TITLE
Topology operator configuration with TLS

### DISCUSSION THREAD

**Discussion by marcelloraffaele** [rabbitmq/messaging-topology-operator#330] [Q&A]
Hi Team,
I have configured my Topology Operator following the guide: [tls-topology-operator](https://www.rabbitmq.com/kubernetes/operator/tls-topology-operator.html), according to it, I needed to mount the CA secret editing the Deployment manifest:
```
kubectl -n rabbitmq-system patch deployment messaging-topology-operator --patch "spec:
  template:
    spec:
      containers:
      - name: manager
        volumeMounts:
        - mountPath: /etc/ssl/certs/rabbitmq-ca.crt
          name: rabbitmq-ca
          subPath: ca.crt
      volumes:
      - name: rabbitmq-ca
        secret:
          defaultMode: 420
          secretName: rabbitmq-ca"
```
I did it and it's working well.

Unfortunately I noticed that sometimes this "**patch**" disappear, maybe something replace it and the operator stop to work till I patch the deployment again.
Have you Idea if it is normal? Can I do something to make this configuration persistent?
Thank you,
RM
