### DISCUSSION TITLE
Policy that mirrors queues to 2 nodes

### DISCUSSION THREAD

**Discussion by ralphotowo** [rabbitmq/messaging-topology-operator#497] [General]
We have an old installation of RabbitMQ using the now deprecated [diy-kubernetes](https://github.com/rabbitmq/diy-kubernetes-examples) setup guide and are looking to migrate to the new and improved cluster operator. I'm currently stuck trying to replicate the policy below into a kubernetes policy manifest file.

<img width="487" alt="Screenshot 2022-11-17 at 10 04 27" src="https://user-images.githubusercontent.com/1202767/202403004-dc9b8ad1-e4ef-4ba7-b18c-65a8aec723b3.png">

This is the policy file we have that works:
```
apiVersion: rabbitmq.com/v1beta1
kind: Policy
metadata:
  name: staging-ha
spec:
  name: ha
  vhost: "/" 
  pattern: "^(?!amq\\.).*"
  applyTo: "queues"
  priority: 1
  definition: 
    ha-mode: "all"
    ha-sync-mode: "automatic"
    # ha-params: 2
  rabbitmqClusterReference:
    name: rabbitmq-staging
```
The file above when applied results in the following policy:

<img width="487" alt="Screenshot 2022-11-17 at 10 11 14" src="https://user-images.githubusercontent.com/1202767/202404398-a8589429-6d12-4626-8bfd-3602d0b70686.png">

I have tried changing the `ha-mode` to 'exactly' and uncommenting the `ha-params` line to get a policy that matches the one in the screenshot above but I've been unsuccessful with the following error from the messaging topology operator pod's logs:

> Validation failed\n\nha-mode=\"exactly\" takes an integer, none │
> │  given\n","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/bitnami/blacksmith-sandox/rmq-messaging-topology-operator-1.8.0/pkg/mod/sigs.k8s. │
> │ io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/bitnami/blacksmith-sandox/rmq-messagin │
> │ g-topology-operator-1.8.0/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234"} 

I want to mirror my queues across two nodes, not all. Can anyone share steps to accomplish this using the cluster operator?

I can login to one of the pods and manually execute the following, but I'm looking to define it declaratively.
`rabbitmqctl set_policy --priority 1 --apply-to queues ha '^(?!amq\.).*' '{"ha-mode":"exactly","ha-params":2,"ha-sync-mode":"automatic"}'`
