### DISCUSSION TITLE
Unable to see queues/exchanges in rabbimq cluster

### DISCUSSION THREAD

**Discussion by kmr0877** [rabbitmq/messaging-topology-operator#502] [Q&A] [answered]
I installed `rabbitmq-cluster-operator` and `messaging-topology-operator` using below commands
```
- kubectl apply -f "https://github.com/rabbitmq/cluster-operator/releases/latest/download/cluster-operator.yml"

- kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.7.1/cert-manager.yaml

- kubectl get pods --namespace cert-manager

- kubectl apply -f https://github.com/rabbitmq/messaging-topology-operator/releases/latest/download/messaging-topology-operator-with-certmanager.yaml
```
Here are the manifest files used to create rabbitmq cluster and queues. I am unable to see those queues/exchanges when I login to management UI. Not sure what am I missing in here?

rabbitmq cluster
```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: rabbitmq-system
  annotations:
    rabbitmq.com/topology-allowed-namespaces: "default"
spec:
  replicas: 3
  rabbitmq:
    additionalConfig: |
      cluster_formation.node_cleanup.interval=30
      cluster_formation.node_cleanup.only_log_warning=true
      cluster_formation.peer_discovery_backend=rabbit_peer_discovery_k8s
      cluster_partition_handling=pause_minority
      default_pass=rabbitmq_dev_user
      default_user=rabbitmq_dev_user
      disk_free_limit.relative=1.0
      log.console.level=debug
      log.console=true
      log.file=false
      loopback_users.guest=true
      queue_master_locator=min-masters
      vm_memory_high_watermark_paging_ratio=0.75
    additionalPlugins:
      - rabbitmq_amqp1_0
      - rabbitmq_peer_discovery_k8s
  service:
    type: ClusterIP
```
queues and exchanges
```
apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: test-exchange
  namespace: rabbitmq-system
spec:
  name: test-exchange # name of the exchange
  vhost: "/" # default to '/' if not provided
  type: direct
  autoDelete: false
  durable: true
  rabbitmqClusterReference:
    name: rabbitmq-server
    namespace: rabbitmq-system
---
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: test-queue # name of this custom resource; does not have to the same as the actual queue name
  namespace: rabbitmq-system
spec:
  name: test-queue # name of the queue
  autoDelete: false
  durable: true
  type: quorum
  definition:
    queue-mode: lazy
  rabbitmqClusterReference:
    name: rabbitmq-server
    namespace: rabbitmq-system
---
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: exchange-queue-binding
  namespace: rabbitmq-system
spec:
  source: test-exchange # an existing exchange
  destination: test-queue # an existing queue
  destinationType: test-queue# can be 'queue' or 'exchange'
  rabbitmqClusterReference:
    name: rabbitmq-server
    namespace: rabbitmq-system
```
