### DISCUSSION TITLE
Namespace collision with rabbitmq/cluster-operator

### DISCUSSION THREAD

**Discussion by Kamaradeivanov** [rabbitmq/messaging-topology-operator#528] [General]
## Describe the bug
Hello, first thing, thanks for the great job you have done with the both rabbitmq operator.

I'm currently using argocd to deploy rabbitmq in a gitops way. Recently i want to add Messaging Topology Kubernetes Operator to create vhost, policy and user with CRD.

To do that I try to used kustomize to easily deploy `rabbitmq/cluster-operator` and `rabbitmq/messaging-topology-operator` but i'am currently facing a collision because the each operator deployment yaml start with : 

```yaml
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/component: rabbitmq-operator
    app.kubernetes.io/name: rabbitmq-system
    app.kubernetes.io/part-of: rabbitmq
  name: rabbitmq-system
```

## To Reproduce

To do that i' have the following kustomize file 

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/rabbitmq/cluster-operator/releases/download/v2.0.0/cluster-operator.yml
  - https://github.com/rabbitmq/messaging-topology-operator/releases/download/v1.10.0/messaging-topology-operator.yaml
```

Then I run 

```bash
kustomize build .
```

And I got the following error 

```bash
Error: accumulating resources: accumulation err='merging resources from 'https://github.com/rabbitmq/messaging-topology-operator/releases/download/v1.10.0/messaging-topology-operator.yaml': may not add resource with an already registered id: ~G_v1_Namespace|~X|rabbitmq-system': evalsymlink failure on '/tmp/kustomize-377141229/releases/download/v1.10.0/messaging-topology-operator.yaml' : lstat /tmp/kustomize-377141229/releases: no such file or directory
```

**Expected behavior**

In your (documentation)[https://github.com/rabbitmq/messaging-topology-operator/#quickstart] you says that :

```
Before deploying Messaging Topology Operator, you need to have:

1. A Running k8s cluster
2. RabbitMQ [Cluster Operator](https://github.com/rabbitmq/cluster-operator) installed in the k8s cluster
3. A [RabbitMQ cluster](https://github.com/rabbitmq/cluster-operator/tree/main/docs/examples) deployed using the Cluster Operator
```

If the RabbitMQ Cluster Operator must be installed why do you also create the nemaspace in the Messaging Topology Kubernetes Operator ?

## Version and environment information
- kustomize: v4.4.0
- kubectl: v1.24.7
- RabbitMQ Cluster Operator: v2.0.0
- RabbitMQ Messaging Topology Kubernetes Operator: v1.10.0
