### DISCUSSION TITLE
Policy validation error

### DISCUSSION THREAD

**Discussion by massimogallina** [rabbitmq/messaging-topology-operator#636] [Q&A] [answered]
Hi, 
I am trying to create a queue of type stream and its related policy.

This is the manifest that I am using:
```yaml
apiVersion: rabbitmq.com/v1beta1
kind: Policy
metadata:
  name: telegraf-m1
  labels:
    helm.sh/chart: telegraf-0.1.2
    app.kubernetes.io/name: telegraf
    app.kubernetes.io/instance: telegraf-m1
    app.kubernetes.io/version: "1.26.3-alpine"
    app.kubernetes.io/managed-by: Helm
spec:
  name: dih_data_rg270_modbus-policy
  pattern: "dih_data_rg270_modbus"
  applyTo: "queues"
  vhost: "/"
  priority: 0
  definition:
    x-max-length-bytes: 1000000000
    x-max-age: "14D"
  rabbitmqClusterReference:
    name: rabbitmq
    namespace: rabbitmq-system
---
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: telegraf-m1
  labels:
    helm.sh/chart: telegraf-0.1.2
    app.kubernetes.io/name: telegraf
    app.kubernetes.io/instance: telegraf-m1
    app.kubernetes.io/version: "1.26.3-alpine"
    app.kubernetes.io/managed-by: Helm
spec:
  name: dih_data_rg270_modbus
  type: stream
  autoDelete: false
  durable: true
  rabbitmqClusterReference:
    name: rabbitmq
    namespace: rabbitmq-system
```

And I got the following log error from message operator:
```log
{"level":"error","ts":"2023-06-12T14:58:50Z","msg":"Reconciler error","controller":"policy","controllerGroup":"rabbitmq.com","controllerKind":"Policy","Policy":{"name":"telegraf-m1","namespace":"default"},"namespace":"default","name":"telegraf-m1","reconcileID":"8319e14f-ba96-4216-a2de-a750f5174eb1","error":"Error 400 (bad_request): Validation failed\n\n[{&lt;&lt;\"x-max-age\"&gt;&gt;,&lt;&lt;\"14D\"&gt;&gt;},{&lt;&lt;\"x-max-length-bytes\"&gt;&gt;,1000000000}] are not recognised policy settings\n","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:235"}
```

I cannot understand what is the error.
Could someone help me to fix it?

Thanks,
Massimo

**Comment by ChunyiLyu** [comment, marked as answer]
For policies, you generally do not need the `x-` prefix. `x-` are used for setting queue arguments at queue declare. Could you please try
```
apiVersion: rabbitmq.com/v1beta1
kind: Policy
...
spec:
  name: dih_data_rg270_modbus-policy
  pattern: "dih_data_rg270_modbus"
  applyTo: "queues"
  vhost: "/"
  priority: 0
  definition:
    max-length-bytes: 1000000000
    max-age: "14D"
...
```
