### DISCUSSION TITLE
Can't create new vhost because several are already exists

### DISCUSSION THREAD

**Discussion by kimllee** [rabbitmq/messaging-topology-operator#894] [Q&A]
Hello,

I'm creating helm templates to create rabbitmq objects. (Focusing on vhosts)
I can create several but when I add a new a vhost in the values.yaml.
Helm doesn't want to create the new one because the previous ones are already exists.

![image](https://github.com/user-attachments/assets/c49a550c-0d73-4ea8-bf26-7fd6f0f88edf)

Is it normal ? What's happening please ?

Thanks a lot.

RabbitMQ : 3.11.18-debian-11-r0
GKE : 1.28
Messaging topology operator : 1.11.0

**Comment by Zerpet** [comment]
This is likely that Helm is trying to create a `vhost` object that already exists. Since this is your own creation, I can't advise much. As general recommendation, you should template the name of the resources with something variable, for example a list of vhosts `[foo, bar, baz]` could be templated like `foo-vhost, bar-vhost, baz-vhost`.

**Reply by kimllee** [reply]
Hello,
Thank you for your answer. If I provide a list of vhosts how could I use different settings for each of them please ?

```
# RabbitMQ template
{{- if .Values.rabbitMQ.enabled }}
{{- if .Values.rabbitMQ.vhosts_enabled }}
{{- $clusterName := .Values.rabbitMQ.clusterName -}}

{{- range $vhostkey, $value := .Values.rabbitMQ.vhosts }}
---
apiVersion: rabbitmq.com/v1beta1
kind: Vhost
metadata:
  name: {{ $vhostkey }}
  annotations:
   "helm.sh/hook": pre-install, pre-upgrade
   "helm.sh/hook-weight": "0"
   "helm.sh/hook-delete-policy": post-delete

  labels: 
    {{- include "rabbitkimq.labels" $ | nindent 4 }}
spec:
  name: {{ $vhostkey }}
  defaultQueueType: {{ $value.queueType }}
  rabbitmqClusterReference:
    name: {{ $clusterName }}
{{ end }}
{{ end }}
{{ end }}
```

```
# values.yaml
rabbitMQ:
  enabled: true
  clusterName: rabbitmqcluster

  vhosts_enabled: true
  vhosts:
    a:
      queueType: classic
    b:
      queueType: classic
    c:
      queueType: quorum
    d:
      queueType: stream
```
