### ISSUE TITLE
Associate permissions to autogenerated users

### ISSUE THREAD

**Issue by MatteoJoliveau** [rabbitmq/messaging-topology-operator#165]
**Is your feature request related to a problem? Please describe.**
When creating `User` objects with autogenerated credentials (so without using `importCredentialsSecret`), we cannot create `Permission` objects for them because the username is a randomly generated string.

**Describe the solution you'd like**
A good solution would be to not autogenerate the username, and instead use the `User` `metadata.name` field when creating the RabbitMQ user and populating the credentials secret.

**Describe alternatives you've considered**
Another option is to allow referencing a `User` object in the `PermissionSpec`, so that the operator can retrieve the generated username from the secret and use it in the permission.

Example:
```yaml
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: example
spec:
  rabbitmqClusterReference:
    name: example-broker
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: example-user
spec:
  userRef:
    name: example # this is the User above
  vhost: '/'
  permissions:
    configure: '.*'
    write: '.*'
    read: '.*'
  rabbitmqClusterReference:
    name: example-broker

```

**Additional context**
Without this feature, when using autogenerated credentials the operator fails to create `Permission` objects with the error `failed to set permission    {"reconciler group": "rabbitmq.com", "reconciler kind": "Permission", "name": "example-user", "namespace": "example", "user": "example", "vhost": "/", "error": "Error 400 (bad_request): vhost_or_user_not_found"}`
