### ISSUE TITLE
Simplify shovel and federation configuration be referencing other resources

### ISSUE THREAD

**Issue by mkuratczyk** [rabbitmq/messaging-topology-operator#210]
This is just an idea but on my experience of setting up shovel using the Topology Operator.

Currently, when configuring shovel or federation, the user needs to create a secret with source/destination URIs. However, if the source and/or destination clusters are deployed with the Cluster Operator, we could simplify the process by skipping this step and either generating this secret or simply reading existing secrets instead. For example, in the shovel case, rather than creating a secret with `destUri` and `srcUri`, we could allow the user to specify the name of the `RabbitmqCluster` and a `User` resource with credentials that should be used - something like this:
```
apiVersion: rabbitmq.com/v1beta1
kind: Shovel
metadata:
  name: shovel-example
spec:
  name: "shovel-example"
  uriReference:
    src: shovel-source
    dst: shovel-destination
  srcQueue: "source-queue"
  destQueue: "destination-queue"
  rabbitmqClusterReference:
    name: example-rabbit
```

Caveats:
* vhost name is a third piece of data we need for the URI, that is not part of the Cluster nor User - how do we specify that?
* based on the outcomes of https://github.com/rabbitmq/messaging-topology-operator/issues/147, this feature could be limited to single-namespace configurations (we need to agree if we want to read a secret from another namespace and how/when we can do that)
* technically shovel can be deployed to any cluster but in practice it's usually deployed on the source or destination cluster. This means that 3 cluster references (src, dst and the existing `rabbitmqClusterReference`) may be confusing.
