### ISSUE TITLE
Rabbit Topology Operator fails to create a user

### ISSUE THREAD

**Issue by Mercanuis** [rabbitmq/messaging-topology-operator#278]
I'm using both the Cluster and Topology operator along with 1.6.1 of the Cert-manager

Trying to follow the [provided example](https://github.com/rabbitmq/messaging-topology-operator/tree/main/docs/tutorial) I am unable to get my minikube to take the following tutorial yaml

```yaml
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: tutorial
  namespace: xxx #same namespace as the deployed RabbitmqCluster
spec:
  name: tutorial # this will be the name of the queue
  rabbitmqClusterReference:
    name: rabbitmq # name of the RabbitmqCluster
---
apiVersion: v1
kind: Secret
metadata:
  name: user-secret
  namespace: xxx #same namespace as the deployed RabbitmqCluster
type: Opaque
stringData:
  username: test
  password: test
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: tutorial-user
  namespace: xxx #same namespace as the deployed RabbitmqCluster
spec:
  importCredentialsSecret:
    name: user-secret
  rabbitmqClusterReference:
    name: rabbitmq # name of the RabbitmqCluster
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: tutorial-user-permission
  namespace: xxx #same namespace as the deployed RabbitmqCluster
spec:
  vhost: "/"
  user: "test" # name of the created user
  permissions:
    write: ".*"
    configure: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: rabbitmq # name of the RabbitmqCluster
``` 

this is providing a false positive of sorts and I'm not sure what is wrong or what is happening.

```shell
kubectl apply -f example-user-queue.yaml 
queue.rabbitmq.com/tutorial created
secret/user-secret created
user.rabbitmq.com/tutorial-user created
permission.rabbitmq.com/tutorial-user-permission created


 kubectl describe user.rabbitmq.com tutorial-user -n xxx
Name:         tutorial-user
Namespace:    xxx
Labels:       <none>
Annotations:  <none>
API Version:  rabbitmq.com/v1beta1
Kind:         User
Metadata:
  Creation Timestamp:  2021-12-24T03:39:25Z
  Finalizers:
    deletion.finalizers.users.rabbitmq.com
  Generation:  2
  Managed Fields:
    API Version:  rabbitmq.com/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:importCredentialsSecret:
          .:
          f:name:
        f:rabbitmqClusterReference:
          .:
          f:name:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2021-12-24T03:39:25Z
    API Version:  rabbitmq.com/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"deletion.finalizers.users.rabbitmq.com":
      f:spec:
        f:rabbitmqClusterReference:
          f:namespace:
    Manager:      manager
    Operation:    Update
    Time:         2021-12-24T03:39:25Z
    API Version:  rabbitmq.com/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:conditions:
        f:credentials:
          .:
          f:name:
    Manager:         manager
    Operation:       Update
    Subresource:     status
    Time:            2021-12-24T03:39:25Z
  Resource Version:  5108
  UID:               7c32ad90-2571-40ba-85ab-760d29c5e2e6
Spec:
  Import Credentials Secret:
    Name:  user-secret
  Rabbitmq Cluster Reference:
    Name:       rabbitmq
    Namespace:  
Status:
  Conditions:
    Last Transition Time:  2021-12-24T03:39:25Z
    Message:               Error: API responded with a 401 Unauthorized
    Reason:                FailedCreateOrUpdate
    Status:                False
    Type:                  Ready
  Credentials:
    Name:  tutorial-user-user-credentials
Events:
  Type     Reason                  Age                 From             Message
  ----     ------                  ----                ----             -------
  Normal   SuccessfulStatusUpdate  36s                 user-controller  Successfully updated user status
  Warning  FailedDeclare           15s (x13 over 36s)  user-controller  failed to declare user
```

minikube is 
```
minikube version
minikube version: v1.23.2
commit: 0a0ad764652082477c00d51d2475284b5d39ceed
🐳  Preparing Kubernetes v1.22.2 on Docker 20.10.8 ...
```

Looking at the describe I'm getting a 401, even though both Operators, and the Cluster are in the same namespace. Does the Cert Manager need to also be in the same namespace?
