### ISSUE TITLE
messaging dont know to take customizeduser/pass

### ISSUE THREAD

**Issue by hilbabt** [rabbitmq/messaging-topology-operator#293]
Hi team ,

so i start to paly with messaging and its working good when i run it when not customized config.
but if i pass to the rabbitMQ opertor spsifce user/pass i get error

```apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: example-rabbit
  namespace: rabbitmq-service
  annotations:
    rabbitmq.com/topology-allowed-namespaces: "my-app"
spec:
  replicas: 1
---
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: test # name of this custom resource; does not have to the same as the actual queue name
  namespace: my-app
spec:
  name: test-queue # name of the queue
  rabbitmqClusterReference:
    name: example-rabbit
    namespace: rabbitmq-service```

│ {"level":"info","ts":1643579112.6292734,"logger":"controller.queue","msg":"Start reconciling","reconciler group":"rabbitmq.com","reconciler kind":"Queue","name":"test","namespace":"my-app","spec":"{\"name\":\"test-queue\",\"vhost\":\"/\",\"r ││ {"level":"info","ts":1643579112.6354482,"logger":"controller.queue","msg":"Successfully declared queue","reconciler group":"rabbitmq.com","reconciler kind":"Queue","name":"test","namespace":"my-app","queue":"test-queue"}                      ││ {"level":"info","ts":1643579112.6472225,"logger":"controller.queue","msg":"Finished reconciling","reconciler group":"rabbitmq.com","reconciler kind":"Queue","name":"test","namespace":"my-app"}                                                  ││ {"level":"info","ts":1643579112.6474988,"logger":"controller.queue","msg":"Start reconciling","reconciler group":"rabbitmq.com","reconciler kind":"Queue","name":"test","namespace":"my-app","spec":"{\"name\":\"test-queue\",\"vhost\":\"/\",\"r ││ {"level":"info","ts":1643579112.6506987,"logger":"controller.queue","msg":"Successfully declared queue","reconciler group":"rabbitmq.com","reconciler kind":"Queue","name":"test","namespace":"my-app","queue":"test-queue"}                      ││ {"level":"info","ts":1643579112.6580894,"logger":"controller.queue","msg":"Finished reconciling","reconciler group":"rabbitmq.com","reconciler kind":"Queue","name":"test","namespace":"my-app"}                                                


but when i run it like that , when i pass spsifce user/pass

`apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: example-rabbit
  namespace: rabbitmq-service
  annotations:
    rabbitmq.com/topology-allowed-namespaces: "my-app"
spec:
  replicas: 1
  rabbitmq:
    additionalConfig: |
      default_user=admin1
      default_pass=admin1
---
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: test # name of this custom resource; does not have to the same as the actual queue name
  namespace: my-app
spec:
  name: test-queue # name of the queue
  rabbitmqClusterReference:
    name: example-rabbit
    namespace: rabbitmq-service`

i get error

{"level":"error","ts":1643578891.8622336,"logger":"controller.queue","msg":"failed to declare queue","reconciler group":"rabbitmq.com","reconciler kind":"Queue","name":"test","namespace":"my-app","queue":"test-queue","error":"Error: API resp ││ {"level":"error","ts":1643578891.8718367,"logger":"controller.queue","msg":"Reconciler error","reconciler group":"rabbitmq.com","reconciler kind":"Queue","name":"test","namespace":"my-app","error":"Error: API responded with a 401 Unauthorize      


how i need to pass the customie user/pass to the messaging ?

**Comment by sb185296** [comment]
its same problem that i was having last mount ago , no one help me 👎

**Comment by coro** [comment]
Hello @hilbabt and @sb185296, firstly, sorry if we missed your issue!

As you can see [here](https://github.com/rabbitmq/messaging-topology-operator/blob/3ba61647b6335108a7c20ecb1d4c090e4f194f19/internal/cluster_reference.go#L85-L106), the messaging-topology-operator connects to RabbitMQ by using the credentials stored in the credentials secret that the cluster-operator generates for a RabbitmqCluster. If, in that RabbitmqCluster, you override the default username/password as in this config, then that is not reflected in the credentials secret unfortunately.

I do happen to know that a member of our team is working on a feature which will allow you to specify a custom set of credentials to use when connecting to the RabbitmqCluster, which will allow you to use this workflow, but until that's shipped I'm afraid it's not possible right now.

One workaround could be to leave the default user/password for now for the messaging-topology-operator to use, and create Users for everything else.

**Comment by hilbabt** [comment]
Hi team ,

first thanks for your quick responsed.

its somting that i need to take with our mangers, on this deploment way.

are your thinking that is somting that can be add in this sprint ?
we are plaing to go live with that prodact....

thanks agien for the respons :)

**Comment by hilbabt** [comment]
hi ,

so in the past 2 day i play with that.
i am not able to make its work , i not get access to : Can access virtual hosts

![image](https://user-images.githubusercontent.com/97466808/152241533-74fbe376-81c2-4e85-a05d-f192ca6f1d62.png)

what do i missing ?
```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: example-rabbit
  #namespace: rabbitmq-service
  #annotations:
  #  rabbitmq.com/topology-allowed-namespaces: "my-app"
spec:
  replicas: 1
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbit-play-credentials
type: Opaque
stringData:
  username: admin
  password: admin
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: play-user
spec:
  tags: 
  - administrator
  rabbitmqClusterReference:
    name: example-rabbit
    #namespace: rabbitmq-service
  importCredentialsSecret:
    name: rabbit-play-credentials
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: testuser-permission
spec:
  vhost: "/"
  user: "play-user" # name corresponds to the username we provided in "rabbit-play-credentials" secret
  permissions:
    write: ".*"
    configure: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: example-rabbit
    #namespace: rabbitmq-service
```
