### ISSUE TITLE
Allow pre-defined passwords to be used for created User objects

### ISSUE THREAD

**Issue by coro** [rabbitmq/messaging-topology-operator#36]
**Is your feature request related to a problem? Please describe.**
As a user, I would like to optionally provide my own pre-defined passwords for generated User objects rather than rely on those generated by the operator.

**Describe the solution you'd like**
Allow for a new field `User.Spec.importPasswordSecret` which is a `LocalObjectReference` to a Secret containing the password to use when declaring the User. This Secret must contain a key whose value will become the password of the new user:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: credentialsSecret
  namespace: testing
type: Opaque
data:
  credentialList.importUser.password: d2h5YXJleW91bG9va2luZ2hlcmU=
---
apiVersion: rabbitmq.com/v1alpha1
kind: User
metadata:
  name: import-user
  namespace: testing
spec:
  name: import-user
  rabbitmqClusterReference:
    name: rmq
    namespace: rabbitmq-system
  importPasswordSecret:
    name: credentialsSecret
    passwordKey: credentialList.importUser.password # defaults to just 'password'
```

**Handling Updates:**
The initial Secret is not the 'source of truth' for the password, but only the initial source. Once the credential Secret is generated for a user, that is considered the source of truth and any further updates to, or deletion of, the initial secret are ignored.

**Additional context**
Original Issue: #3
