### ISSUE TITLE
Permission: this User does not have an username set in its status

### ISSUE THREAD

**Issue by wasabii** [rabbitmq/messaging-topology-operator#363]
Can't seem to get permissions to apply. Getting this error. I have a User resource, which is being created correctly. However, it is not putting username on User.Status.

This worked in some previous version of the operator.

`{"level":"error","ts":1651702129.0251908,"logger":"controller.permission","msg":"Reconciler error","reconciler group":"rabbitmq.com","reconciler kind":"Permission","name":"accutraq-rabbitmq-keda","namespace":"accutraq","error":"this Use ││ r does not have an username set in its status","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/bitnami/blacksmith-sandox/rmq-messaging-topology-operator-1.5.0/pkg/mod/sigs.k8s.i ││ o/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/bitnami/blacksmith-sandox/rmq-messaging-topology-operator-1.5.0/pkg/mod/sigs. ││ k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:227"}`

**Comment by wasabii** [comment]
Looks like I am running 1.5.0.

I found the code in users_controller.go that does this check. Yeah. It expects it to exist. I also found code that is supposed to set it on status.username in the case of a "migration". I am assuming that the idea here is that an old version didn't have status.username.... but a new version does.... and this is supposed to add it? It's not. Also, I've tried deploying my RabbtMqCluster and User/Permission resources from complete scratch, with no luck. Clean install on 1.5.0 ends in this error.

**Comment by wasabii** [comment]
Downgrading to a helm chart that packages 1.4.1 fixed the issue. Downgraded, issue gone. No other changes.

**Comment by wasabii** [comment]
So, the combination that doesn't work is cluster operator 1.12.1 and topology operator 1.5.0.

The combination that does work is cluster operator 1.12.1 and topology operator 1.4.1.

By manifest, do you mean the resources?

User:

```
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  annotations:
    meta.helm.sh/release-name: accutraq
    meta.helm.sh/release-namespace: accutraq
  creationTimestamp: "2022-05-05T13:50:58Z"
  finalizers:
  - deletion.finalizers.users.rabbitmq.com
  generation: 1
  labels:
    app.kubernetes.io/instance: accutraq
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: accutraq
    app.kubernetes.io/version: 1.4.0-alpha.95
    helm.sh/chart: accutraq-1.4.0-alpha.95
  name: accutraq-rabbitmq
  namespace: accutraq
  resourceVersion: "30672734"
  uid: ef540df7-2ddf-400c-af90-203d3842789e
spec:
  rabbitmqClusterReference:
    name: accutraq-rabbitmq
status:
  conditions:
  - lastTransitionTime: "2022-05-05T13:57:47Z"
    reason: SuccessfulCreateOrUpdate
    status: "True"
    type: Ready
  credentials:
    name: accutraq-rabbitmq-user-credentials
  observedGeneration: 1
```

Permission:
```
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  annotations:
    meta.helm.sh/release-name: accutraq
    meta.helm.sh/release-namespace: accutraq
  creationTimestamp: "2022-05-05T13:50:57Z"
  finalizers:
  - deletion.finalizers.permissions.rabbitmq.com
  generation: 1
  labels:
    app.kubernetes.io/instance: accutraq
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: accutraq
    app.kubernetes.io/version: 1.4.0-alpha.95
    helm.sh/chart: accutraq-1.4.0-alpha.95
  name: accutraq-rabbitmq
  namespace: accutraq
  resourceVersion: "30672873"
  uid: 75c694bb-bc08-4e50-885e-1de22adbf4c7
spec:
  permissions:
    configure: .*
    read: .*
    write: .*
  rabbitmqClusterReference:
    name: accutraq-rabbitmq
  userReference:
    name: accutraq-rabbitmq
  vhost: /
status:
  conditions:
  - lastTransitionTime: "2022-05-05T13:58:01Z"
    reason: SuccessfulCreateOrUpdate
    status: "True"
    type: Ready
  observedGeneration: 1
```

**Comment by ChunyiLyu** [comment]
@wasabii I cannot reproduce the issue with the same topology operator and cluster operator (`1.5` and `1.21.1`). I used user and permission manifest:

```yaml
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: example
spec:
  tags:
  - administrator
  rabbitmqClusterReference:
    name: sample
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: example-permission
spec:
  vhost: "/"
  userReference:
    name: example
  permissions:
    write: ".*"
    configure: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: sample
```

and a generated user was created with correct permissions set in server:
```bash
rabbitmq@sample-server-0:/$ rabbitmqctl list_users
Listing users ...
user	tags
default_user_k0uTpC3eoOqvEJMywbd	[administrator]
l_kudB6gmJOjhbia1flYac6thl-gTDs1	[administrator]
rabbitmq@sample-server-0:/$ rabbitmqctl list_permissions
Listing permissions for vhost "/" ...
user	configure	write	read
l_kudB6gmJOjhbia1flYac6thl-gTDs1	.*	.*	.*
default_user_k0uTpC3eoOqvEJMywbd	.*	.*	.*
```
If you could still reproduce the issue in your testing environment, I think a longer log snippet from the topology operator could be useful to see why username isn't set in the user status.

**Comment by raman-antanevich** [comment]
Seems the issue was caused by using deprecated CRD (`users.rabbitmq.com`). For instance, I have a Kubernetes cluster where operator `v1.3.0` was installed some time ago. During upgrading to the latest version I started getting the same error.

I noticed that `User` resource didn't have `username` field in `status` block which was added in 98086fa1882e4988dffd5126c424cae6b9fe5a90.

```yaml
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  annotations:
    meta.helm.sh/release-name: rabbitmq-cluster
    meta.helm.sh/release-namespace: dev-01
  creationTimestamp: "2022-04-02T14:21:02Z"
  finalizers:
  - deletion.finalizers.users.rabbitmq.com
  generation: 2
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: rabbitmq-cluster
    app.kubernetes.io/version: 3.8.21
    helm.sh/chart: rabbitmq-cluster-1.3.2
  name: atlas
  namespace: dev-01
spec:
  importCredentialsSecret:
    name: atlas-rabbitmq-user
  rabbitmqClusterReference:
    name: rabbitmq-cluster
status:
  conditions:
  - lastTransitionTime: "2022-04-02T14:21:02Z"
    reason: SuccessfulCreateOrUpdate
    status: "True"
    type: Ready
  credentials:
    name: atlas-user-credentials
  observedGeneration: 2
```

Then I manually updated `users.rabbitmq.com` and the problem was solved:

```sh
kubectl apply -f ./config/crd/bases/rabbitmq.com_users.yaml
```

As you can see `status.username` appeared and topology operator could provision `Permission` resources:

```yaml
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  annotations:
    meta.helm.sh/release-name: rabbitmq-cluster
    meta.helm.sh/release-namespace: dev-01
  creationTimestamp: "2022-04-02T14:21:02Z"
  finalizers:
  - deletion.finalizers.users.rabbitmq.com
  generation: 2
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: rabbitmq-cluster
    app.kubernetes.io/version: 3.8.21
    helm.sh/chart: rabbitmq-cluster-1.3.2
  name: atlas
  namespace: dev-01
spec:
  importCredentialsSecret:
    name: atlas-rabbitmq-user
  rabbitmqClusterReference:
    name: rabbitmq-cluster
status:
  conditions:
  - lastTransitionTime: "2022-04-02T14:21:02Z"
    reason: SuccessfulCreateOrUpdate
    status: "True"
    type: Ready
  credentials:
    name: atlas-user-credentials
  observedGeneration: 2
  username: atlas
```

Operator logs: 

```
{"level":"info","ts":1655120237.9337282,"logger":"controller.permission","msg":"Start reconciling","reconciler group":"rabbitmq.com","reconciler kind":"Permission","name":"atlas","namespace":"dev-01","spec":"{\"userReference\":{\"name\":\"atlas\"},\"vhost\":\"/\",\"permissions\":{\"configure\":\".*\",\"write\":\".*\",\"read\":\".*\"},\"rabbitmqClusterReference\":{\"name\":\"rabbitmq-cluster\"}}"}
{"level":"info","ts":1655120237.9424405,"logger":"controller.permission","msg":"Successfully set permission","reconciler group":"rabbitmq.com","reconciler kind":"Permission","name":"atlas","namespace":"dev-01","user":"atlas","vhost":"/"}
{"level":"info","ts":1655120237.9516056,"logger":"controller.permission","msg":"Finished reconciling","reconciler group":"rabbitmq.com","reconciler kind":"Permission","name":"atlas","namespace":"dev-01"}
```
