### ISSUE TITLE
Provide a Provisioned Service Binding custom resource

### ISSUE THREAD

**Issue by coro** [rabbitmq/messaging-topology-operator#39]
**Is your feature request related to a problem? Please describe.**
Currently, an application must be configured with access data from many different resources: Vhosts & user credentials from a Secret owned by a `rabbitmq.com/v1alpha1.User` object, and Service host/ports from a `rabbitmq.com/v1beta1.RabbitmqCluster`. The format of these Objects is not consistent with other Kubernetes provisioned services.

**Describe the solution you'd like**
We should expose a higher-level abstraction of these concepts into a new CRD, a ProvisionedServiceBinding:

```yaml
apiVersion: rabbitmq.com/v1alpha1
kind: ProvisionedServiceBinding
metadata:
  name: binding-foo
  namespace: example
spec:
  <...> # Whatever configuration is required for configuring users, vhosts, anything that is included in a binding
  rabbitmqClusterReference:
    name: rmq
    namespace: example
```

This will create (alongside the lower level resources) a Secret with a signature following the [Provisioned Service Spec](https://k8s-service-bindings.github.io/spec/#provisioned-service):
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: production-rabbit
  namespace: production
type: service.binding/amqps
stringData:
  type: amqps
  provider: rabbitmq
  host: example.com
  port: 5671
  username: foo
  password: bar
```

**Describe alternatives you've considered**
From @st3v : "There's also different implementation approaches we might want to discuss when it comes to the binding resource type, e.g. developing a dedicated reconciler for a RabbitMQ binding vs relying on a more declarative approach to resource composition."

**Additional context**
Original Issue: #3
