### ISSUE TITLE
`Secret` name created  for `User` CRD is not specific enough

### ISSUE THREAD

**Issue by kriswuollett** [rabbitmq/messaging-topology-operator#407]
## Describe the bug

When the `User` CRD is used, a `Secret` is generated with the credentials. The name used follows the format `${user}-user-credentials`. That is too generic of a name since any server could have come up with that naming scheme, and so there is the potential for conflicts. I can tell it was created by the operator due to its metadata:

```yaml
metadata:
  creationTimestamp: "[SOME TIMESTAMP]"
  name: apiserver-user-credentials
  namespace: my-namespace
  ownerReferences:
  - apiVersion: rabbitmq.com/v1beta1
    blockOwnerDeletion: false
    controller: true
    kind: User
    name: apiserver
    uid: "[SOME UID]"
type: Opaque
```

Instead it may be better to use a pattern like `rabbitmq-${clusterName}-${user}-user-credentials`.
