### ISSUE TITLE
Near duplicate `Secret` created when `importCredentialsSecret` used with `User` CRD

### ISSUE THREAD

**Issue by kriswuollett** [rabbitmq/messaging-topology-operator#408]
The `messaging-topology-operator` creates a new `Secret` with name `${user}-user-credentials` even though I specified `importCredentialsSecret` with name `rabbitmq-${cluster}-${user}-credentials`. The operator should be able to watch the existing secret that is being referenced, and possibly just do some management operation like remove all permissions / deny login to user if the imported secret does not exist.

It is a problem because it both seems unnecessary, as well as can cause naming conflicts, see #407.

## To Reproduce

Using Terraform I'm creating the users like:

```hcl
locals {
  users = {
    "apiserver" = {}
  }
}

resource "random_password" "user" {
  for_each = local.users

  length = 16
}

resource "kubernetes_secret_v1" "user_password" {
  for_each = random_password.user

  metadata {
    name        = "rabbitmq-${kubernetes_manifest.rabbitmq.object.metadata.name}-${each.key}-credentials"
    namespace   = var.kubernetes_namespace
    labels      = var.kubernetes_labels
    annotations = var.kubernetes_annotations
  }
  type = "kubernetes.io/basic-auth"
  data = {
    username = each.key
    password = each.value.result
  }
}

resource "kubernetes_manifest" "user" {
  for_each = kubernetes_secret_v1.user_password

  manifest = {
    apiVersion = "rabbitmq.com/v1beta1"
    kind       = "User"
    metadata = {
      name        = each.key
      namespace   = var.kubernetes_namespace
      labels      = var.kubernetes_labels
      annotations = var.kubernetes_annotations
    }
    spec = {
      rabbitmqClusterReference = {
        name = kubernetes_manifest.rabbitmq.object.metadata.name
      }
      importCredentialsSecret = {
        name = each.value.metadata[0].name
      }
    }
  }
}
```

## Version and environment information
- Messaging Topology Operator: v1.7.0
- RabbitMQ: 3.10.2
- RabbitMQ Cluster Operator: v1.14.0
- Kubernetes:
  - Client Version: v1.24.1
  - Kustomize Version: v4.5.4
  - Server Version: v1.22.8-gke.201
- Cloud provider or hardware configuration: GKE

**Comment by kriswuollett** [comment]
The issue may be that `importCredentialsSecret` was ignored, here is the user status, I'd expect to see my secret name in `credentials.name`:

```yaml
spec:
  importCredentialsSecret:
    name: rabbitmq-pubsub-apiserver-credentials
  rabbitmqClusterReference:
    name: pubsub
status:
  conditions:
  - lastTransitionTime: "2022-06-27T19:42:32Z"
    reason: SuccessfulCreateOrUpdate
    status: "True"
    type: Ready
  credentials:
    name: apiserver-user-credentials
  observedGeneration: 1
  username: apiserver
```
