### ISSUE TITLE
When using vault, setting the VAULT_ADDR via deployment doesn't work (OpenShift/OLM setup)

### ISSUE THREAD

**Issue by erikrs** [rabbitmq/messaging-topology-operator#500]
## Describe the bug
When setting the env variable on the deployment, the action is immediately undone (by the operator, since the deployment is managed by it.)

## To Reproduce
1. By following the "vault-support" example, as suggested in the docs (https://www.rabbitmq.com/kubernetes/operator/vault-topology-operator.html), the relevant step as described is:
```
kubectl set env deployment/messaging-topology-operator -n rabbitmq-system --containers='manager' OPERATOR_VAULT_ROLE=messaging-topology-operator VAULT_ADDR=http://vault.$CURRENT_KUBE_NAMESPACE.svc.cluster.local:8200
```
(line 29 of test.sh, https://github.com/rabbitmq/messaging-topology-operator/blob/main/docs/examples/vault-support/test.sh)

2. When performed in an OpenShift environment (version 4.10), the environment variables get applied but seconds later the deployment is changed back to previous state (probably by the operator).

**Expected behavior**
The VAULT_ADDR env. variable should be applied without being undone.

**my view on it and workaround**
I don't know if adapting a deployment controlled by an operator is best-practice (or works in another K8s setup as OpenShift, since I only tried it there).

But my understanding is that adapting it in the deployment isn't the correct place. It is controlled by the operator and more specific in the ClusterServiceVersion object, since there is the 'template' of the deployment and its pod specs etc..

I got it to work by doing this:

```
cat clusterserviceversion-patch.yaml
- op: add
  path: /spec/install/spec/deployments/0/spec/template/spec/containers/0/env/-
  value:
    name: VAULT_ADDR
    value: http://vault-active.vault.svc.cluster.local:8200

oc patch ClusterServiceVersion rabbitmq-messaging-topology-operator.v1.10.0 --type='json' --patch-file=clusterserviceversion-patch.yaml
```

As such, setting the  VAULT_ADDR should be configurable in the operator then (somehow?)

## Version and environment information
- Messaging Topology Operator: 1.10.0
- RabbitMQ Cluster Operator: 2.0.0
- Kubernetes: OpenShift 4.10.14 (Kubernetes version 1.23)
