### ISSUE TITLE
Topology Operator should support multiple references to the same VHost

### ISSUE THREAD

**Issue by zorlack** [rabbitmq/messaging-topology-operator#665]
**Is your feature request related to a problem? Please describe.**
When writing messaging applications my team typically makes it the responsibility of each application to create its own required message queue resources. **This allows the applications to start in any order and keeps the configuration of the messaging environment close to the application code.**

In the kubernetes world we have continued this such that:  
- `Application A` has a helm chart which publishes a deployment and all of the necessary Topology CRs. 
- `Application B` consumes messages published by `Application A` and also has a helm chart.

The helm chart produces something like this for `Application A`:
```
apiVersion: rabbitmq.com/v1beta1
kind: Vhost
metadata:
  name: application-a-vhost
  namespace: default
spec:
  name: /test
  rabbitmqClusterReference:
    name: my-first-cluster
---
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: application-a-input-queue
  namespace: default
spec:
  durable: true
  name: application-a-input
  rabbitmqClusterReference:
    name: my-first-cluster
  vhost: /test
---
apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: application-a-output-exchange
  namespace: default
spec:  
  name: application-handoff-exchange
  type: topic
  autoDelete: false
  durable: true  
  rabbitmqClusterReference:
    name: my-first-cluster
  vhost: /test  
```
And something like this, for `Application B`:
```
apiVersion: rabbitmq.com/v1beta1
kind: Vhost
metadata:
  name: application-b-vhost
  namespace: default
spec:
  name: /test
  rabbitmqClusterReference:
    name: my-first-cluster
---
apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: application-b-input-exchange
  namespace: default
spec:  
  name: application-handoff-exchange
  type: topic
  autoDelete: false
  durable: true  
  rabbitmqClusterReference:
    name: my-first-cluster
  vhost: /test     
---
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: application-b-input-queue
  namespace: default
spec:
  durable: true
  name: application-b-input
  rabbitmqClusterReference:
    name: my-first-cluster
  vhost: /test
```

I've omitted some key elements but you can see that `application-a-vhost` and `application-b-vhost` point to the same vhost.

The problem comes when I'd like to delete `Application B`. **Deleting the `application-b-vhost` record results in the deletion of the resource required by `application-a-vhost`**.  

For a little while the queues, exchanges, bindings etc. have all been deleted from the messaging environment. Then, eventually they will be recreated (if all the resources are spec'd in kubernetes and time-based reconciliation is effective.)

**Describe the solution you'd like**
I'm not sure what the solution here is. At it's smallest you could apply certain rules when deleting vhosts to prevent deletion in the case that there's another reference to the same object.

But if you did that you might want to take it further and apply similar logic to all objects...

_And then it feels like you're talking about configurable reconciliation strategies..._

**Describe alternatives you've considered**

Well, the alternative for me was kind of painful because the Topology Operator kept restoring `deletion.finalizers.vhosts.rabbitmq.com` to the CR whenever I'd try to sneakily delete the resource.

1: Stop the topology-operator
2: Delete the ValidatingWebhook
3: Remove the finalizer from the duplicate vhost CR
4: Delete the duplcate vhost CR
5: Recreate the ValidatingWebhook
6: Restart the topology-operator

**Additional context**
I'm perfectly happy to be told that this topic was covered in the documentation. But if it was I couldn't find it... 

Thanks very much!

-Z
