### ISSUE TITLE
webhooks fail in deployment without cert-manager

### ISSUE THREAD

**Issue by shanehughes** [rabbitmq/messaging-topology-operator#701]
## Describe the bug
Deploying 1.12.1 into an OpenShift cluster without cert-manager results in failure to process resources due to invalid certificates. I posted some commentary in #683, but realise it is _possibly_ a build issue.

## To Reproduce
1. Deploy 1.12.1 into a cluster WITHOUT cert-manager - that is, a straight up OLM deployment
2. Create any type of resource - TopicPermission (for example)
3. See the error in the logs - 

Suspicious looking YAML in the resulting Deployment - see [comments](https://github.com/rabbitmq/messaging-topology-operator/discussions/683#discussioncomment-7560338).

**Expected behavior**
Resources correctly processed by the webhook.

## Version and environment information
- Messaging Topology Operator: 1.12.1
- RabbitMQ Cluster Operator: 2.5.0

**Comment by DanielePalaia** [comment]
Hi @shanehughes 

Actually at the moment we have few issues with OKD cluster we normally use for testing.

But anyway I made a few tests using crc locally.

I'm not meeting any issue here these are the manifests I used (I didn't install cert-manager):

OperatorGroup
``` 
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: test-og
  namespace: rabbitmq-system 
spec:
  targetNamespaces:
  - rabbitmq-system 
 ```

Subscriptions:
```
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: trivy-operator
  namespace: rabbitmq-system 
spec:
  channel: stable 
  installPlanApproval: Automatic
  name: rabbitmq-cluster-operator
  source: community-operators
  sourceNamespace: openshift-marketplace 
  startingCSV: rabbitmq-cluster-operator.v2.5.0 
```

```
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: trivy-operator-2
  namespace: rabbitmq-system 
spec:
  channel: stable 
  installPlanApproval: Automatic
  name: rabbitmq-messaging-topology-operator
  source: community-operators
  sourceNamespace: openshift-marketplace 
  startingCSV: rabbitmq-messaging-topology-operator.v1.12.1 
```

RabbitMQ cluster
```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: hello-world
  namespace: rabbitmq-system
spec:
  service:
    type: LoadBalancer
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers: []
            securityContext: {}
```

Operators seem up and running.
I tried then to load a few objects using the messaging operator like
```
kind: User
metadata:
  name: user-sample
spec:
  tags:
  - management # available tags are 'management', 'policymaker', 'monitoring' and 'administrator'
  rabbitmqClusterReference:
    name: hello-world  # rabbitmqCluster must exist in the same namespace as this resource
```
```
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: qq-example
spec:
  name: qq # name of the queue
  vhost: "/" # default to '/' if not provided
  type: quorum # without providing a queue type, rabbitmq creates a classic queue
  autoDelete: false
  durable: true # seting 'durable' to false means this queue won't survive a server restart
  rabbitmqClusterReference:
    name: hello-world # rabbitmqCluster must exist in the same namespace as this resource
```

```
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: testuser-permission
spec:
  vhost: "/" # name of a vhost
  user: "DSAvdQ9AvqBMrcpeiTbw47Zi8moafxDP" # name of a RabbitMQ user
  permissions:
    write: ".*"
    configure: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: hello-world  # rabbitmqCluster must exist in the same namespace as this resource
```

Are you experimenting this with all resorces or just TopicPermission?

**Comment by shanehughes** [comment]
Apologies, after some diving through deployed CRDs, I found a couple that hadn't been correctly replaced during the cut-over to the OperatorHub managed deployments from our old hand-deployed approach. These had some of the erroneous material in left in them. I've managed to get the operator up and running correctly now.

The only outstanding 'issue' (if you could call it that) is the superfluous `cert` mount on the pod itself:

```
 volumes:
    - name: cert    <--- Not used
      secret:
        secretName: webhook-server-cert
        defaultMode: 420
    - name: apiservice-cert
    ...
```
This isn't bound (or used) anywhere, I suspect it's a hangover from the certmanager integration?
