### ISSUE TITLE
Bindings status is not right after the bound exchange removed and re-created

### ISSUE THREAD

**Issue by stararks** [rabbitmq/messaging-topology-operator#754]
## Describe the bug
While the exchange that was bound to a queue is removed, the binding status is still showing successfully with the deleted exchange even it is bound to the default exchange. After the exchange was re-created.  It is still bound to the default exchange but not the one declared in spec.

## To Reproduce
1. Create exchange
```
kubectl apply -f - <<EOF
apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: exchange.test
  namespace: default
spec:
  durable: true
  name: exchange.test
  rabbitmqClusterReference:
    name: rabbitmq
    namespace: rabbitmq
  type: topic
  vhost: testhost
EOF
```

2. Create queue
```
kubectl apply -f - <<EOF
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: queue.test
  namespace: default
spec:
  durable: true
  name: queue.test
  rabbitmqClusterReference:
    name: rabbitmq
    namespace: rabbitmq
  vhost: testhost
EOF
```

3. Create bindings
```
kubectl apply -f - <<EOF
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: exchange.test-queue.test
  namespace: default
spec:
  destination: queue.test
  destinationType: queue
  rabbitmqClusterReference:
    name: rabbitmq
    namespace: rabbitmq
  routingKey: key.test
  source: exchange.test
  vhost: testhost
EOF
```

4. Delete Exchange 
```
kubectl delete -f - <<EOF
apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: exchange.test
  namespace: default
spec:
  durable: true
  name: exchange.test
  rabbitmqClusterReference:
    name: rabbitmq
    namespace: rabbitmq
  type: topic
  vhost: testhost
EOF
```

The binding status is as below, but actually, it is bound to default exchange (checked via UI)
```
kubectl describe bindings.rabbitmq.com exchange.test-queue.test
Name:         exchange.test-queue.test
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  rabbitmq.com/v1beta1
Kind:         Binding
Metadata:
  Creation Timestamp:  2024-01-30T03:54:48Z
  Finalizers:
    deletion.finalizers.bindings.rabbitmq.com
  Generation:        1
  Resource Version:  809625
  UID:               664e9ca1-79c3-4a59-bf25-a4046fb2ce61
Spec:
  Destination:       queue.test
  Destination Type:  queue
  Rabbitmq Cluster Reference:
    Name:       rabbitmq
    Namespace:  rabbitmq
  Routing Key:  key.test
  Source:       exchange.test
  Vhost:        testhost
Status:
  Conditions:
    Last Transition Time:  2024-01-30T03:54:48Z
    Reason:                SuccessfulCreateOrUpdate
    Status:                True
    Type:                  Ready
  Observed Generation:     1
Events:
  Type    Reason             Age                    From                Message
  ----    ------             ----                   ----                -------
  Normal  SuccessfulDeclare  9m55s (x3 over 9m55s)  binding-controller  Successfully declare binding
```

5. Re-create the exchange 
```
kubectl apply -f - <<EOF
apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: exchange.test
  namespace: default
spec:
  durable: true
  name: exchange.test
  rabbitmqClusterReference:
    name: rabbitmq
    namespace: rabbitmq
  type: topic
  vhost: testhost
EOF
```

The queue is still bound to the default exchange.

**Expected behavior**
The operator should update the binding status when the exchange status needs to be changed. i.e. When the exchange was deleted, the binding status should show it is bound to a new exchange. When the exchange is re-created, the binding should be recovered to bind the exchange that is decleared in the spec.

## Version and environment information
- Messaging Topology Operator:  v1.12.1
- RabbitMQ: 3.12.2
- RabbitMQ Cluster Operator: v2.6.0
- Kubernetes:  v1.26.4+k3s1
- Cloud provider or hardware configuration: Ubuntu 20.04 on Azure
- k3d version v5.5.0
- k3s version v1.26.4-k3s1 (default)
