### ISSUE TITLE
Resources created by the messaging-topology-operator exists and can be used but the listing details in the management UI returns not found on the resource

### ISSUE THREAD

**Issue by msschl** [rabbitmq/messaging-topology-operator#849]
## Describe the bug
Resources created by the messaging-topology-operator exists and can be used by producers and consumers.
When trying to access the resource in the management UI it returns "not found" for the resource

```log
Not found

The object you clicked on was not found; it may have been deleted on the server.
```

## To Reproduce
```yaml
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-ha
  namespace: rabbitmq
spec:
  replicas: 3
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 1Gi
  rabbitmq:
    additionalConfig: |
      cluster_partition_handling = pause_minority
      vm_memory_high_watermark_paging_ratio = 0.99
      disk_free_limit.relative = 1.0
      collect_statistics_interval = 10000
      loopback_users = none
  secretBackend:
    vault:
      role: rabbitmq-rabbitmq-ha
      defaultUserPath: configuration/data/rabbitmq/rabbitmq-ha/credentials
  persistence:
    storageClassName: vsphere-block
    storage: "10Gi"
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - rabbitmq-ha
        topologyKey: kubernetes.io/hostname
# Start region '/dev' development
---
apiVersion: rabbitmq.com/v1beta1
kind: Vhost
metadata:
  name: dev-vhost
  namespace: rabbitmq
spec:
  name: /dev
  rabbitmqClusterReference:
    name: rabbitmq-ha
---
# Start region '/' production
---
apiVersion: rabbitmq.com/v1beta1
kind: Vhost
metadata:
  name: prod-vhost
  namespace: rabbitmq
spec:
  name: /
  defaultQueueType: quorum
  rabbitmqClusterReference:
    name: rabbitmq-ha
```

**Expected behavior**
Created resources by the messaging-topology-operator are shown in the management UI

## Screenshots
As you can see the virtual hosts are created by the messaging-topology-operator 
![image](https://github.com/rabbitmq/messaging-topology-operator/assets/5054780/c2f1ff29-c688-43fd-b4a3-b5a4a71aed50)

Clicking on the resource results in:
![image](https://github.com/rabbitmq/messaging-topology-operator/assets/5054780/5a7462a4-a552-418f-9113-62789eb33bab)

## Version and environment information
- Messaging Topology Operator: v1.14.2
- RabbitMQ: 3.13.2
- RabbitMQ Cluster Operator: 2.9.0
- Kubernetes: 1.29.6
 
## Additional context
Using all created resources from code, i.e., our running services, also works:
![image](https://github.com/rabbitmq/messaging-topology-operator/assets/5054780/86188de4-ec50-4084-8aaf-6decd3cdff91)
