### ISSUE TITLE
Add vhost limits

### ISSUE THREAD

**Issue by MirahImage** [rabbitmq/messaging-topology-operator#963]
RabbitMQ supports [vhost limits](https://www.rabbitmq.com/docs/vhosts#limits). It would be nice to configure these limits via the messaging topology operator.

**Describe the solution you'd like**
An optional additional Limits section in the vhost spec to specify limits. This is akin to the user limits added in #962

**Comment by battly** [comment]
Excuse the question for I am relatively new to RabbitMQ and using the Messaging Topology Operator - when can we expect to have the manifest file allowing use to set the vhost limits? 

Is it possible already? I would appreaciate a short response.

**Comment by Zerpet** [comment]
It is possible already. For example:

```yaml
apiVersion: rabbitmq.com/v1beta1
kind: Vhost
metadata:
  name: test-vhost
spec:
  name: myvhost
  rabbitmqClusterReference:
    name: test
  limits:
    connections: 100
    queues: 50
```
